export enum Environment {
  Showroom = "Place this vehicle in a premium automotive showroom with polished concrete flooring that shows subtle reflections. Use soft, professional studio lighting from multiple angles to eliminate harsh shadows while creating gentle highlights on the vehicle's curves. The background should feature clean white or light gray walls with subtle architectural elements like columns or glass panels. Add warm accent lighting (3000K color temperature) to create an upscale ambiance. Ensure the vehicle casts a soft, diffused shadow on the glossy floor. The lighting should emphasize the vehicle's paint finish and make it appear pristine and showroom-ready. Keep the background minimal and professional - no cluttered displays or distracting elements.",
  Urban = "Stage this vehicle on a clean urban street with modern city architecture in the background. Use evening/dusk lighting (golden hour or blue hour) with atmospheric street lights, neon signs, and ambient city glow. Include textured pavement or cobblestone streets that show realistic wear. Add environmental elements like brick walls with street art or murals, modern storefronts with illuminated signs, and subtle atmospheric effects like light steam or mist. Ensure the vehicle's shadows match the direction and intensity of the street lighting. Create depth with blurred background buildings and distant city lights. The scene should feel cinematic and aspirational, making the vehicle look dynamic and urban-sophisticated. Include realistic reflections of neon lights on the vehicle's paint and windows.",
  Mountain = "Position this vehicle on a scenic mountain road or overlook with dramatic natural landscapes in the background. Use late afternoon or early morning lighting that creates long, natural shadows and warm golden tones. Include winding asphalt roads with painted lane markers, mountain peaks in the distance, and evergreen trees or rocky terrain. The road surface should show realistic texture and the vehicle should have shadows that match the sun angle. Add atmospheric depth with layers of mountains fading into the distance (atmospheric perspective with blue tones). For SUVs and trucks, consider including elements like gravel shoulders or slight dust around the tires to suggest capability. The environment should convey adventure and freedom while keeping the vehicle as the clear focal point. Ensure proper color temperature - cooler blues in shadows, warmer tones in sunlit areas.",
  Coastal = "Place this vehicle on a coastal road or beachside location with ocean views in the background. Use bright, natural daylight with clear skies (either morning or late afternoon light for softer shadows). Include elements like a paved coastal highway with ocean barriers or railings, sandy beaches in the mid-ground, and blue ocean water with gentle waves in the background. Add palm trees or coastal vegetation if appropriate for the setting. The lighting should be bright and airy with slightly cooler color temperatures (5500-6000K) to match the coastal atmosphere. Ensure the vehicle's paint reflects the blue sky and ocean colors subtly. Include realistic shadows on the pavement that match the sun position. The scene should feel open, spacious, and vacation-inspired. For convertibles or lifestyle vehicles, this setting should emphasize freedom and leisure.",
  Dealership = "Stage this vehicle in a professional outdoor dealership setting with clean, well-maintained asphalt or concrete lot surface. Use daytime natural lighting (10 AM - 2 PM sun angle) that provides even, clear illumination with moderate shadows. The background should include subtle dealership elements like other vehicles slightly out of focus, modern dealership building architecture with large windows or glass facades, and branded signage at an appropriate distance. Include parking lot striping (white or yellow lines) and ensure the surface looks clean and professional. Add elements like: flags or banners in the background, landscaped areas with maintained grass or shrubs, and a clear sky (blue with minimal clouds). The vehicle should have natural shadows underneath that match the overhead sun position. The overall aesthetic should be clean, professional, and trustworthy - making customers feel confident about the dealership's quality. Avoid overly dramatic lighting; keep it realistic and approachable."
}

export type EnvironmentKey = keyof typeof Environment;

export enum Accessory {
  RoofRack = 'a sleek, black roof rack suitable for the vehicle type',
  CustomWheels = 'stylish, larger custom alloy wheels with a matte black finish',
  WindowTint = 'a dark, professional-grade tint to the side and rear windows',
  BlackoutTrim = 'a "blackout" package, changing all chrome trim (like the grille and window surrounds) to a glossy black finish',
}

export type AccessoryKey = keyof typeof Accessory;